// Code generated by mockery v2.32.4. DO NOT EDIT.

package mocks

import (
	context "context"

	store "github.com/spiretechnology/go-webauthn/store"
	mock "github.com/stretchr/testify/mock"
)

// MockCredentials is an autogenerated mock type for the Credentials type
type MockCredentials struct {
	mock.Mock
}

type MockCredentials_Expecter struct {
	mock *mock.Mock
}

func (_m *MockCredentials) EXPECT() *MockCredentials_Expecter {
	return &MockCredentials_Expecter{mock: &_m.Mock}
}

// GetCredential provides a mock function with given fields: ctx, userID, credentialID
func (_m *MockCredentials) GetCredential(ctx context.Context, userID string, credentialID []byte) (*store.Credential, error) {
	ret := _m.Called(ctx, userID, credentialID)

	var r0 *store.Credential
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string, []byte) (*store.Credential, error)); ok {
		return rf(ctx, userID, credentialID)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string, []byte) *store.Credential); ok {
		r0 = rf(ctx, userID, credentialID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*store.Credential)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string, []byte) error); ok {
		r1 = rf(ctx, userID, credentialID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockCredentials_GetCredential_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetCredential'
type MockCredentials_GetCredential_Call struct {
	*mock.Call
}

// GetCredential is a helper method to define mock.On call
//   - ctx context.Context
//   - userID string
//   - credentialID []byte
func (_e *MockCredentials_Expecter) GetCredential(ctx interface{}, userID interface{}, credentialID interface{}) *MockCredentials_GetCredential_Call {
	return &MockCredentials_GetCredential_Call{Call: _e.mock.On("GetCredential", ctx, userID, credentialID)}
}

func (_c *MockCredentials_GetCredential_Call) Run(run func(ctx context.Context, userID string, credentialID []byte)) *MockCredentials_GetCredential_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string), args[2].([]byte))
	})
	return _c
}

func (_c *MockCredentials_GetCredential_Call) Return(_a0 *store.Credential, _a1 error) *MockCredentials_GetCredential_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockCredentials_GetCredential_Call) RunAndReturn(run func(context.Context, string, []byte) (*store.Credential, error)) *MockCredentials_GetCredential_Call {
	_c.Call.Return(run)
	return _c
}

// GetCredentials provides a mock function with given fields: ctx, userID
func (_m *MockCredentials) GetCredentials(ctx context.Context, userID string) ([]store.Credential, error) {
	ret := _m.Called(ctx, userID)

	var r0 []store.Credential
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string) ([]store.Credential, error)); ok {
		return rf(ctx, userID)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string) []store.Credential); ok {
		r0 = rf(ctx, userID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]store.Credential)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = rf(ctx, userID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockCredentials_GetCredentials_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetCredentials'
type MockCredentials_GetCredentials_Call struct {
	*mock.Call
}

// GetCredentials is a helper method to define mock.On call
//   - ctx context.Context
//   - userID string
func (_e *MockCredentials_Expecter) GetCredentials(ctx interface{}, userID interface{}) *MockCredentials_GetCredentials_Call {
	return &MockCredentials_GetCredentials_Call{Call: _e.mock.On("GetCredentials", ctx, userID)}
}

func (_c *MockCredentials_GetCredentials_Call) Run(run func(ctx context.Context, userID string)) *MockCredentials_GetCredentials_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string))
	})
	return _c
}

func (_c *MockCredentials_GetCredentials_Call) Return(_a0 []store.Credential, _a1 error) *MockCredentials_GetCredentials_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockCredentials_GetCredentials_Call) RunAndReturn(run func(context.Context, string) ([]store.Credential, error)) *MockCredentials_GetCredentials_Call {
	_c.Call.Return(run)
	return _c
}

// StoreCredential provides a mock function with given fields: ctx, userID, credential
func (_m *MockCredentials) StoreCredential(ctx context.Context, userID string, credential store.Credential) error {
	ret := _m.Called(ctx, userID, credential)

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, string, store.Credential) error); ok {
		r0 = rf(ctx, userID, credential)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockCredentials_StoreCredential_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'StoreCredential'
type MockCredentials_StoreCredential_Call struct {
	*mock.Call
}

// StoreCredential is a helper method to define mock.On call
//   - ctx context.Context
//   - userID string
//   - credential store.Credential
func (_e *MockCredentials_Expecter) StoreCredential(ctx interface{}, userID interface{}, credential interface{}) *MockCredentials_StoreCredential_Call {
	return &MockCredentials_StoreCredential_Call{Call: _e.mock.On("StoreCredential", ctx, userID, credential)}
}

func (_c *MockCredentials_StoreCredential_Call) Run(run func(ctx context.Context, userID string, credential store.Credential)) *MockCredentials_StoreCredential_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string), args[2].(store.Credential))
	})
	return _c
}

func (_c *MockCredentials_StoreCredential_Call) Return(_a0 error) *MockCredentials_StoreCredential_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockCredentials_StoreCredential_Call) RunAndReturn(run func(context.Context, string, store.Credential) error) *MockCredentials_StoreCredential_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockCredentials creates a new instance of MockCredentials. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockCredentials(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockCredentials {
	mock := &MockCredentials{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
